CREATE DATABASE blog;
CREATE TABLE `blog`.`users` ( `id` INT(11) NOT NULL , `username` VARCHAR(255) NOT NULL , `password` VARCHAR(255) NOT NULL , `first_name` VARCHAR(255) NOT NULL , `last_name` VARCHAR(255) NOT NULL , `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP , `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP , PRIMARY KEY (`id`)) ENGINE = InnoDB;
CREATE TABLE `blog`.`categories` ( `id` INT(11) NOT NULL , `name` VARCHAR(255) NOT NULL , `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP , `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP , PRIMARY KEY (`id`)) ENGINE = InnoDB;
CREATE TABLE `blog`.`posts` ( `id` INT(11) NOT NULL AUTO_INCREMENT , `category_id` INT(11) NOT NULL , `author` VARCHAR(255) NOT NULL , `title` VARCHAR(255) NOT NULL , `image` TEXT NOT NULL , `content` TEXT NOT NULL , `tags` VARCHAR(255) NOT NULL , `comments_count` INT(11) NOT NULL , `status` VARCHAR(255) NOT NULL , `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP , `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP , PRIMARY KEY (`id`)) ENGINE = InnoDB;
ALTER TABLE `categories` CHANGE `id` `id` INT(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `users` CHANGE `id` `id` INT(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `posts` CHANGE `comments_count` `comments_count` INT( 11 ) NOT NULL DEFAULT '0';
ALTER TABLE `posts` CHANGE `comments_count` `comments_count` INT( 11 ) NULL DEFAULT '0';
ALTER TABLE `posts` CHANGE `author` `user_id` INT(11) NOT NULL;
ALTER TABLE `categories` ADD `user_id` INT(11) NOT NULL AFTER `id`;
ALTER TABLE `users` ADD `role` VARCHAR(255) NULL DEFAULT 'User' AFTER `id`;
UPDATE `users` SET `role` = 'Super User' WHERE `users`.`id` = 1;
ALTER TABLE `posts` DROP `comments_count`;
CREATE TABLE IF NOT EXISTS `uploads` (`id` int(11) NOT NULL AUTO_INCREMENT,`user_id` int(11) NOT NULL,`title` varchar(255) NOT NULL,`description` text,`filename` varchar(255) NOT NULL,`type` varchar(255) NOT NULL,`size` varchar(255) NOT NULL,`created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,`updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY (`id`)) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=2;
